name: python-env
channels:
  - conda-forge
dependencies:
  - python=3.12.5
  - boto
  - beautifulsoup4
  - git
  - lxml
  - matplotlib
  - numpy
  - nvim
  - pandas
  - parallel
  - pre-commit
  - requests
  - s3fs
  - scikit-learn
  - seaborn